# Generated by Django 3.2.5 on 2022-01-10 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveling_events', models.CharField(max_length=200, null=True)),
                ('music_events', models.CharField(max_length=200, null=True)),
                ('clothing_fashion', models.CharField(max_length=200, null=True)),
                ('web_projects', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, null=True)),
                ('user_name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapi.category')),
            ],
        ),
    ]
