# Generated by Django 3.2.5 on 2022-01-10 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0002_addpost_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='clothing_fashion',
            new_name='name_of_categories',
        ),
        migrations.RemoveField(
            model_name='category',
            name='music_events',
        ),
        migrations.RemoveField(
            model_name='category',
            name='traveling_events',
        ),
        migrations.RemoveField(
            model_name='category',
            name='web_projects',
        ),
    ]
