# Generated by Django 3.2.5 on 2022-01-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0003_auto_20220110_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpost',
            old_name='comments',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='addpost',
            name='user_name',
        ),
        migrations.AddField(
            model_name='addpost',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addpost',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
