# Generated by Django 3.2.5 on 2022-01-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0004_auto_20220110_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='media/')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='addpost',
            name='message',
        ),
        migrations.AddField(
            model_name='addpost',
            name='blog_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addpost',
            name='description',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='addpost',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addpost',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
