# Generated by Django 3.2.5 on 2022-01-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0005_auto_20220110_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpost',
            name='categories',
        ),
        migrations.AlterField(
            model_name='addpost',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
