# Generated by Django 3.2.5 on 2022-01-10 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0006_auto_20220110_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpost',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapi.category'),
        ),
    ]
