# Generated by Django 3.2.5 on 2022-01-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0007_addpost_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpost',
            name='categories',
        ),
    ]
