# Generated by Django 3.2.5 on 2022-01-10 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0008_remove_addpost_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpost',
            name='categories1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapi.category'),
        ),
    ]
