# Generated by Django 3.2.5 on 2022-01-11 13:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0009_addpost_categories1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='description',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
    ]
