# Generated by Django 3.2.5 on 2022-01-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0011_auto_20220112_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(choices=[('good', 'good'), ('verygood', 'verygood'), ('best', 'best'), ('excellent', 'excellent')], max_length=300, null=True),
        ),
    ]
